solution/fp
Al-Fro/study pull request #2
Opened 2020-04-23 12:32 UTC by Al-Fro

2020-04-23 14:39 UTC, pn-y requested changes

2020-04-23 14:39 UTC, pn-y commented on test/exercise/fp/solution.rb
> +          !key_country.nil? && key_country.split(',').length >= 2 && !key_rating.nil? && key_rating != 0
`!key_country.nil?` повторяется

2020-04-23 14:39 UTC, pn-y commented on test/exercise/fp/solution.rb
> +        sort_array.map { |film| film['rating_kinopoisk'].to_f }.reduce(:+) / sort_array.length
Сложно.  Разнеси на разные строки подсчет рейтинга и использование

2020-04-24 06:14 UTC, Al-Fro commented on test/exercise/fp/solution.rb
> +          !key_country.nil? && key_country.split(',').length >= 2 && !key_rating.nil? && key_rating != 0
там разные переменные `!key_country.nil?` и `!key_rating.nil?`, если я правильно понял замечание

2020-04-24 06:20 UTC, Al-Fro commented on test/exercise/fp/solution.rb
> +        sort_array.map { |film| film['rating_kinopoisk'].to_f }.reduce(:+) / sort_array.length
исправил

2020-04-25 19:02 UTC, Andrew8xx8 requested changes

2020-04-25 19:02 UTC, Andrew8xx8 commented on test/exercise/fp/solution.rb
> +          !key_country.nil? && key_country.split(',').length >= 2 && !key_rating.nil? && key_rating != 0
Зачем `!.nil?` если есть просто `.present?`. Для читаемости кода всегда лучше использовать методы-антонимы, чем добавлять отрицание.

2020-04-25 19:02 UTC, Andrew8xx8 commented on test/exercise/fp/solution.rb
> +          !key_country.nil? && key_country.split(',').length >= 2 && !key_rating.nil? && key_rating != 0
Переменные да, разные

2020-04-26 08:47 UTC, Al-Fro commented on test/exercise/fp/solution.rb
> +          !key_country.nil? && key_country.split(',').length >= 2 && !key_rating.nil? && key_rating != 0
переделал

2020-04-28 12:00 UTC, pn-y requested changes

2020-04-28 12:00 UTC, pn-y commented on test/exercise/fp/solution.rb
> +        sort_array.map { |film| film['name'] }.join('').split('').select { |el| el.include?('и') }.size
Правильно, но сложно. На строке можно вызвать `count`

2020-04-28 12:29 UTC, Al-Fro commented on test/exercise/fp/solution.rb
> +        sort_array.map { |film| film['name'] }.join('').split('').select { |el| el.include?('и') }.size
Исправил

2020-04-29 11:43 UTC, Andrew8xx8 approved these changes

2020-04-29 17:59 UTC, merged